<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYfw7xtv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYfw7xtv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYfw7xtv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYfw7xtv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYfw7xtv\appProdProjectContainer([
    'container.build_hash' => 'Yfw7xtv',
    'container.build_id' => 'e9b5a01e',
    'container.build_time' => 1634681199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYfw7xtv');
